In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.svm import SVR
from sklearn.preprocessing import MinMaxScaler, StandardScaler

In [2]:
dataset = pd.read_csv("new cases dataset.csv", index_col='date', parse_dates=True)
print('shape',dataset.shape)
dataset.describe()

shape (500, 11)


total_cases    new_cases  total_deaths  new_deaths  \
count     500.000000   500.000000    500.000000  500.000000   
mean    52728.956000   204.206000    383.742000    1.646000   
std     32793.093696   296.233164    281.213438    3.354876   
min         3.000000     0.000000      0.000000    0.000000   
25%     26460.250000     0.000000    142.750000    0.000000   
50%     50544.000000    89.000000    323.000000    0.000000   
75%     89893.000000   281.250000    734.000000    2.000000   
max    102103.000000  1583.000000    823.000000   28.000000   

       reproduction_rate  positive_rate  total_vaccinations  \
count         500.000000     500.000000        5.000000e+02   
mean            1.122480       0.068814        2.869641e+04   
std             0.263627       0.061634        1.613339e+05   
min             0.000000       0.000000        0.000000e+00   
25%             0.997500       0.023000        0.000000e+00   
50%             1.170000       0.045000        0.000000e+00   
75%             1.252500       0.100000        0.000000e+00   
max             1.550000       0.319000        1.271393e+06   

       people_vaccinated  people_fully_vaccinated  new_vaccinations  \
count         500.000000               500.000000         500.00000   
mean        24776.272000              3920.140000         241.36000   
std        133943.541915             39060.971015        3144.28997   
min             0.000000                 0.000000           0.00000   
25%             0.000000                 0.000000           0.00000   
50%             0.000000                 0.000000           0.00000   
75%             0.000000                 0.000000           0.00000   
max        865422.000000            405971.000000       48252.00000   

       stringency_index  
count        500.000000  
mean          47.446220  
std           12.460919  
min            0.000000  
25%           38.890000  
50%           44.440000  
75%           52.780000  
max           86.110000

In [3]:
X = dataset[['positive_rate']]
Y = dataset[['new_cases']]
scaler= MinMaxScaler()
X=scaler.fit_transform(X)
Y = scaler.fit_transform(Y)

In [4]:
from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size= 0.10, random_state=123, shuffle=False) 

In [5]:
from sklearn.svm import SVR
linSVR = SVR(kernel='linear')
linSVR.fit(X_train, Y_train.ravel())

polySVR = SVR(kernel='poly', degree=2)
polySVR.fit(X_train, Y_train.ravel())

rbfSVR = SVR(kernel='rbf', C=1000.0, gamma=0.15)
rbfSVR.fit(X_train, Y_train.ravel())

SVR(C=1000.0, gamma=0.15)

In [6]:
Y_pred = polySVR.predict(X_test)

In [7]:
Y_pred

array([0.0923944 , 0.09192875, 0.09268544, 0.09253507, 0.09203061,
       0.09226344, 0.09203061, 0.09203061, 0.09319475, 0.09301528,
       0.09301528, 0.09301528, 0.09284551, 0.09284551, 0.09379138,
       0.09338393, 0.09253507, 0.09268544, 0.09226344, 0.09214217,
       0.09268544, 0.09253507, 0.0923944 , 0.09423763, 0.09379138,
       0.09379138, 0.09497977, 0.0964107 , 0.09610511, 0.09472269,
       0.09472269, 0.09738567, 0.09705098, 0.09705098, 0.09882145,
       0.09773007, 0.09920465, 0.09580923, 0.09672599, 0.09610511,
       0.09738567, 0.09672599, 0.09144369, 0.09144369, 0.09144369,
       0.09144369, 0.09144369, 0.09144369, 0.09144369, 0.09144369])

In [8]:
Y_test

array([[0.        ],
       [0.        ],
       [0.08907138],
       [0.        ],
       [0.0473784 ],
       [0.03095389],
       [0.        ],
       [0.        ],
       [0.13013266],
       [0.07896399],
       [0.        ],
       [0.05622236],
       [0.        ],
       [0.        ],
       [0.09222994],
       [0.11181301],
       [0.        ],
       [0.01452937],
       [0.        ],
       [0.        ],
       [0.06948831],
       [0.06759318],
       [0.10486418],
       [0.17182565],
       [0.        ],
       [0.        ],
       [0.09665193],
       [0.15792798],
       [0.05369551],
       [0.        ],
       [0.19330385],
       [0.16614024],
       [0.        ],
       [0.1004422 ],
       [0.28742893],
       [0.        ],
       [0.09033481],
       [0.        ],
       [0.24384081],
       [0.        ],
       [0.20277953],
       [0.24131396],
       [0.        ],
       [0.2166772 ],
       [0.        ],
       [0.        ],
       [0.68856601],
       [0.313

In [9]:
Y_pred.reshape(-1,1)

array([[0.0923944 ],
       [0.09192875],
       [0.09268544],
       [0.09253507],
       [0.09203061],
       [0.09226344],
       [0.09203061],
       [0.09203061],
       [0.09319475],
       [0.09301528],
       [0.09301528],
       [0.09301528],
       [0.09284551],
       [0.09284551],
       [0.09379138],
       [0.09338393],
       [0.09253507],
       [0.09268544],
       [0.09226344],
       [0.09214217],
       [0.09268544],
       [0.09253507],
       [0.0923944 ],
       [0.09423763],
       [0.09379138],
       [0.09379138],
       [0.09497977],
       [0.0964107 ],
       [0.09610511],
       [0.09472269],
       [0.09472269],
       [0.09738567],
       [0.09705098],
       [0.09705098],
       [0.09882145],
       [0.09773007],
       [0.09920465],
       [0.09580923],
       [0.09672599],
       [0.09610511],
       [0.09738567],
       [0.09672599],
       [0.09144369],
       [0.09144369],
       [0.09144369],
       [0.09144369],
       [0.09144369],
       [0.091

In [10]:
y_testvy_pred =pd.concat([pd.DataFrame(Y_test), pd.DataFrame(Y_pred)], axis=1)

In [11]:
rev_trans= scaler.inverse_transform(y_testvy_pred)

In [12]:
rev_trans

array([[   0.        ,  146.26034141],
       [   0.        ,  145.52320521],
       [ 141.        ,  146.72105154],
       [   0.        ,  146.48301797],
       [  75.        ,  145.68445376],
       [  49.        ,  146.05302185],
       [   0.        ,  145.68445376],
       [   0.        ,  145.68445376],
       [ 206.        ,  147.52729425],
       [ 125.        ,  147.24318968],
       [   0.        ,  147.24318968],
       [  89.        ,  147.24318968],
       [   0.        ,  146.9744421 ],
       [   0.        ,  146.9744421 ],
       [ 146.        ,  148.47175001],
       [ 177.        ,  147.82675583],
       [   0.        ,  146.48301797],
       [  23.        ,  146.72105154],
       [   0.        ,  146.05302185],
       [   0.        ,  145.8610593 ],
       [ 110.        ,  146.72105154],
       [ 107.        ,  146.48301797],
       [ 166.        ,  146.26034141],
       [ 272.        ,  149.1781722 ],
       [   0.        ,  148.47175001],
       [   0.        ,  1

In [13]:
final= pd.DataFrame(rev_trans)

In [17]:
final.columns=['new_cases','predicted']
final

new_cases   predicted
0         0.0  146.260341
1         0.0  145.523205
2       141.0  146.721052
3         0.0  146.483018
4        75.0  145.684454
5        49.0  146.053022
6         0.0  145.684454
7         0.0  145.684454
8       206.0  147.527294
9       125.0  147.243190
10        0.0  147.243190
11       89.0  147.243190
12        0.0  146.974442
13        0.0  146.974442
14      146.0  148.471750
15      177.0  147.826756
16        0.0  146.483018
17       23.0  146.721052
18        0.0  146.053022
19        0.0  145.861059
20      110.0  146.721052
21      107.0  146.483018
22      166.0  146.260341
23      272.0  149.178172
24        0.0  148.471750
25        0.0  148.471750
26      153.0  150.352983
27      250.0  152.618141
28       85.0  152.134396
29        0.0  149.946022
30      306.0  149.946022
31      263.0  154.161520
32        0.0  153.631703
33      159.0  153.631703
34      455.0  156.434357
35        0.0  154.706694
36      143.0  157.040958
37        0.0  151.666007
38      386.0  153.117244
39        0.0  152.134396
40      321.0  154.161520
41      382.0  153.117244
42        0.0  144.755355
43      343.0  144.755355
44        0.0  144.755355
45        0.0  144.755355
46     1090.0  144.755355
47      497.0  144.755355
48      423.0  144.755355
49      933.0  144.755355

In [15]:
from sklearn.metrics import mean_absolute_error
mae_new_cases = mean_absolute_error(final['predicted'],final['new_cases'])
print('Mean absolute error of new cases is:',mae_new_cases)

Mean absolute error of new cases is: 154.59852180869657
