In [1]:
import pandas as pd
import numpy as np
import os
import matplotlib.pyplot as plt
import time
from xgboost import XGBRegressor
from sklearn.model_selection import train_test_split
from tensorflow.keras.preprocessing.sequence import TimeseriesGenerator as gen
from sklearn.preprocessing import MinMaxScaler, StandardScaler

In [2]:
col_list=["date","new_cases","positive_rate"]
dataset = pd.read_csv("new cases dataset.csv",usecols=col_list)
dataset.describe()

new_cases  positive_rate
count   500.000000     500.000000
mean    204.206000       0.068814
std     296.233164       0.061634
min       0.000000       0.000000
25%       0.000000       0.023000
50%      89.000000       0.045000
75%     281.250000       0.100000
max    1583.000000       0.319000

In [3]:
dataset['date']=pd.to_datetime(dataset['date'], infer_datetime_format= True)
df= dataset.loc[:,dataset.columns !='date']

In [4]:
scaler= MinMaxScaler()

dataScaled=scaler.fit_transform(df)

In [5]:
features= dataScaled
target= dataScaled[:,0]

In [6]:
X_train, X_test, Y_train, Y_test = train_test_split(features, target, test_size= 0.10, random_state=123, shuffle=False) 

In [7]:
model = XGBRegressor(n_estimators=500, learning_rate=0.01)
model.fit(X_train,Y_train, eval_set=[(X_train, Y_train),(X_test, Y_test)], eval_metric= 'mae')

[0]	validation_0-mae:0.38814	validation_1-mae:0.40757
[1]	validation_0-mae:0.38431	validation_1-mae:0.40355
[2]	validation_0-mae:0.38052	validation_1-mae:0.39957
[3]	validation_0-mae:0.37676	validation_1-mae:0.39563
[4]	validation_0-mae:0.37305	validation_1-mae:0.39172
[5]	validation_0-mae:0.36937	validation_1-mae:0.38786
[6]	validation_0-mae:0.36572	validation_1-mae:0.38403
[7]	validation_0-mae:0.36211	validation_1-mae:0.38025
[8]	validation_0-mae:0.35854	validation_1-mae:0.37654
[9]	validation_0-mae:0.35500	validation_1-mae:0.37284
[10]	validation_0-mae:0.35149	validation_1-mae:0.36919
[11]	validation_0-mae:0.34802	validation_1-mae:0.36557
[12]	validation_0-mae:0.34459	validation_1-mae:0.36197
[13]	validation_0-mae:0.34119	validation_1-mae:0.35843
[14]	validation_0-mae:0.33783	validation_1-mae:0.35489
[15]	validation_0-mae:0.33449	validation_1-mae:0.35140
[16]	validation_0-mae:0.33119	validation_1-mae:0.34796
[17]	validation_0-mae:0.32792	validation_1-mae:0.34449
[18]	validation_0-ma

[295]	validation_0-mae:0.02094	validation_1-mae:0.02216
[296]	validation_0-mae:0.02073	validation_1-mae:0.02194
[297]	validation_0-mae:0.02053	validation_1-mae:0.02173
[298]	validation_0-mae:0.02033	validation_1-mae:0.02153
[299]	validation_0-mae:0.02013	validation_1-mae:0.02132
[300]	validation_0-mae:0.01993	validation_1-mae:0.02112
[301]	validation_0-mae:0.01973	validation_1-mae:0.02091
[302]	validation_0-mae:0.01954	validation_1-mae:0.02072
[303]	validation_0-mae:0.01935	validation_1-mae:0.02052
[304]	validation_0-mae:0.01916	validation_1-mae:0.02032
[305]	validation_0-mae:0.01897	validation_1-mae:0.02013
[306]	validation_0-mae:0.01879	validation_1-mae:0.01994
[307]	validation_0-mae:0.01860	validation_1-mae:0.01975
[308]	validation_0-mae:0.01842	validation_1-mae:0.01956
[309]	validation_0-mae:0.01824	validation_1-mae:0.01937
[310]	validation_0-mae:0.01806	validation_1-mae:0.01919
[311]	validation_0-mae:0.01788	validation_1-mae:0.01901
[312]	validation_0-mae:0.01771	validation_1-mae:

[442]	validation_0-mae:0.00492	validation_1-mae:0.00574
[443]	validation_0-mae:0.00487	validation_1-mae:0.00569
[444]	validation_0-mae:0.00483	validation_1-mae:0.00564
[445]	validation_0-mae:0.00478	validation_1-mae:0.00559
[446]	validation_0-mae:0.00473	validation_1-mae:0.00554
[447]	validation_0-mae:0.00469	validation_1-mae:0.00550
[448]	validation_0-mae:0.00464	validation_1-mae:0.00545
[449]	validation_0-mae:0.00460	validation_1-mae:0.00540
[450]	validation_0-mae:0.00455	validation_1-mae:0.00536
[451]	validation_0-mae:0.00451	validation_1-mae:0.00531
[452]	validation_0-mae:0.00446	validation_1-mae:0.00527
[453]	validation_0-mae:0.00442	validation_1-mae:0.00522
[454]	validation_0-mae:0.00438	validation_1-mae:0.00518
[455]	validation_0-mae:0.00433	validation_1-mae:0.00514
[456]	validation_0-mae:0.00429	validation_1-mae:0.00509
[457]	validation_0-mae:0.00425	validation_1-mae:0.00505
[458]	validation_0-mae:0.00421	validation_1-mae:0.00501
[459]	validation_0-mae:0.00417	validation_1-mae:

XGBRegressor(base_score=0.5, booster='gbtree', colsample_bylevel=1,
             colsample_bynode=1, colsample_bytree=1, gamma=0, gpu_id=-1,
             importance_type='gain', interaction_constraints='',
             learning_rate=0.01, max_delta_step=0, max_depth=6,
             min_child_weight=1, missing=nan, monotone_constraints='()',
             n_estimators=500, n_jobs=4, num_parallel_tree=1, random_state=0,
             reg_alpha=0, reg_lambda=1, scale_pos_weight=1, subsample=1,
             tree_method='exact', validate_parameters=1, verbosity=None)

In [8]:
predictions =model.predict(X_test)

In [9]:
predictions

array([0.00363357, 0.00363357, 0.0930251 , 0.00363357, 0.0504058 ,
       0.03409975, 0.00363357, 0.00363357, 0.1338271 , 0.08168966,
       0.00363357, 0.05924363, 0.00363357, 0.00363357, 0.09429731,
       0.11439551, 0.00363357, 0.01841345, 0.00363357, 0.00363357,
       0.07178211, 0.07115673, 0.10751227, 0.17400695, 0.00363357,
       0.00363357, 0.09933505, 0.16084623, 0.05671911, 0.00363357,
       0.19728306, 0.16774525, 0.00363357, 0.10310408, 0.2887861 ,
       0.00363357, 0.0930251 , 0.00363357, 0.2479621 , 0.00363357,
       0.20546022, 0.2479621 , 0.00363357, 0.21672939, 0.00363357,
       0.00363357, 0.7043327 , 0.31581149, 0.27125242, 0.58078605],
      dtype=float32)

In [10]:
predictions.reshape(-1,1)

array([[0.00363357],
       [0.00363357],
       [0.0930251 ],
       [0.00363357],
       [0.0504058 ],
       [0.03409975],
       [0.00363357],
       [0.00363357],
       [0.1338271 ],
       [0.08168966],
       [0.00363357],
       [0.05924363],
       [0.00363357],
       [0.00363357],
       [0.09429731],
       [0.11439551],
       [0.00363357],
       [0.01841345],
       [0.00363357],
       [0.00363357],
       [0.07178211],
       [0.07115673],
       [0.10751227],
       [0.17400695],
       [0.00363357],
       [0.00363357],
       [0.09933505],
       [0.16084623],
       [0.05671911],
       [0.00363357],
       [0.19728306],
       [0.16774525],
       [0.00363357],
       [0.10310408],
       [0.2887861 ],
       [0.00363357],
       [0.0930251 ],
       [0.00363357],
       [0.2479621 ],
       [0.00363357],
       [0.20546022],
       [0.2479621 ],
       [0.00363357],
       [0.21672939],
       [0.00363357],
       [0.00363357],
       [0.7043327 ],
       [0.315

In [1]:
predvtest = pd.concat([pd.DataFrame(Y_test), pd.DataFrame(predictions)], axis=1)

NameError: name 'pd' is not defined

In [12]:
rev_trans= scaler.inverse_transform(predvtest)

In [13]:
rev_trans

array([[0.00000000e+00, 1.15910821e-03],
       [0.00000000e+00, 1.15910821e-03],
       [1.41000000e+02, 2.96750079e-02],
       [0.00000000e+00, 1.15910821e-03],
       [7.50000000e+01, 1.60794491e-02],
       [4.90000000e+01, 1.08778191e-02],
       [0.00000000e+00, 1.15910821e-03],
       [0.00000000e+00, 1.15910821e-03],
       [2.06000000e+02, 4.26908465e-02],
       [1.25000000e+02, 2.60590002e-02],
       [0.00000000e+00, 1.15910821e-03],
       [8.90000000e+01, 1.88987182e-02],
       [0.00000000e+00, 1.15910821e-03],
       [0.00000000e+00, 1.15910821e-03],
       [1.46000000e+02, 3.00808426e-02],
       [1.77000000e+02, 3.64921690e-02],
       [0.00000000e+00, 1.15910821e-03],
       [2.30000000e+01, 5.87389133e-03],
       [0.00000000e+00, 1.15910821e-03],
       [0.00000000e+00, 1.15910821e-03],
       [1.10000000e+02, 2.28984938e-02],
       [1.07000000e+02, 2.26989977e-02],
       [1.66000000e+02, 3.42964127e-02],
       [2.72000000e+02, 5.55082183e-02],
       [0.000000

In [14]:
final= pd.DataFrame(rev_trans)

In [15]:
final.columns=['new_cases','predicted']
final

new_cases  predicted
0         0.0   0.001159
1         0.0   0.001159
2       141.0   0.029675
3         0.0   0.001159
4        75.0   0.016079
5        49.0   0.010878
6         0.0   0.001159
7         0.0   0.001159
8       206.0   0.042691
9       125.0   0.026059
10        0.0   0.001159
11       89.0   0.018899
12        0.0   0.001159
13        0.0   0.001159
14      146.0   0.030081
15      177.0   0.036492
16        0.0   0.001159
17       23.0   0.005874
18        0.0   0.001159
19        0.0   0.001159
20      110.0   0.022898
21      107.0   0.022699
22      166.0   0.034296
23      272.0   0.055508
24        0.0   0.001159
25        0.0   0.001159
26      153.0   0.031688
27      250.0   0.051310
28       85.0   0.018093
29        0.0   0.001159
30      306.0   0.062933
31      263.0   0.053511
32        0.0   0.001159
33      159.0   0.032890
34      455.0   0.092123
35        0.0   0.001159
36      143.0   0.029675
37        0.0   0.001159
38      386.0   0.079100
39        0.0   0.001159
40      321.0   0.065542
41      382.0   0.079100
42        0.0   0.001159
43      343.0   0.069137
44        0.0   0.001159
45        0.0   0.001159
46     1090.0   0.224682
47      497.0   0.100744
48      423.0   0.086530
49      933.0   0.185271

In [16]:
from sklearn.metrics import mean_absolute_error
mae_new_cases = mean_absolute_error(final['predicted'],final['new_cases'])
print('Mean absolute error of new cases is:',mae_new_cases)

Mean absolute error of new cases is: 157.46819767186216


In [17]:
dataset

date  new_cases  positive_rate
0   2020-03-14        3.0            0.0
1   2020-03-15        3.0            0.0
2   2020-03-16        0.0            0.0
3   2020-03-17        1.0            0.0
4   2020-03-18        0.0            0.0
..         ...        ...            ...
495 2021-07-22        0.0            0.0
496 2021-07-23     1090.0            0.0
497 2021-07-24      497.0            0.0
498 2021-07-25      423.0            0.0
499 2021-07-26      933.0            0.0

[500 rows x 3 columns]

In [ ]:
train= dataset.iloc[:-50]
test= dataset.iloc[-50:]
print(train.shape,test.shape)